// Generated by CoffeeScript 1.3.3
(function() {
  var $, canvas, context, drawing, effects, headtrackr, htracker, resize2, sparklePos, video,
    __slice = [].slice;

  $ = require('jquery-browserify');

  headtrackr = require('headtrackr');

  video = document.getElementById('inputVideo');

  canvas = document.getElementById('inputCanvas');

  effects = document.getElementById('effectCanvas');

  context = effects.getContext('2d');

  htracker = new headtrackr.Tracker();

  htracker.init(video, canvas);

  htracker.start();

  resize2 = function(i) {
    var cc, ctx;
    cc = document.createElement("canvas");
    cc.width = i.width / 2;
    cc.height = i.height / 2;
    ctx = cc.getContext("2d");
    ctx.drawImage(i, 0, 0, cc.width, cc.height);
    return cc;
  };

  sparklePos = [0, 0];

  drawing = new Image();

  drawing.src = "nyancat2.png";

  $(document).on('facetrackingEvent', function(ev) {
    var cat;
    cat = drawing;
    ev = ev.originalEvent;
    sparklePos = [ev.x - cat.width / 2, ev.y - cat.height / 2 - 40];
    context.clearRect(0, 0, 320, 240);
    return context.drawImage.apply(context, [cat].concat(__slice.call(sparklePos)));
  });

}).call(this);
