// Generated by CoffeeScript 1.3.3
(function() {
  var bearingS, bearingSmoothS, directionS, f;

  f = {
    floor: function(v) {
      return Math.floor(v);
    }
  };

  directionS = $(window).asEventStream('deviceorientation').map('.originalEvent');

  bearingS = directionS.map(function(ev) {
    return ev.alpha;
  });

  bearingSmoothS = bearingS.slidingWindow(25).map(function(vs) {
    return _.inject(vs, (function(s, n) {
      return s + n;
    }), 0) / vs.length;
  });

  bearingS.map(f.floor).assign($('.bearing-smooth'), 'text');

  bearingSmoothS.map(f.floor).assign($('.bearing'), 'text');

}).call(this);
